
name: Django Tests
# on:
#   push:
#     branches:
#       -main
#   pull_request:
#     branches:
#       -main
on: [ push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup python 3.9.6
      uses: actions/setup -python@v2
      with:
        python_version: 3.9.6
    - name: install dependencies
      run:  |
        python -m pip install --upgrade pip
        pip install -r requirement.txt
    - name: Lint with flake8
      run:  |
        pip install flake8
        flake8
    - name: Coverage report
      run:  |
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: Django Testing
      run:  |
        python3 manage.py test
