
name: Djando Tests
on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
job:
  build:
    run_on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: setup python 3.9.6
      uses: actions/setup -python@v2
      with:
       python_version: 3.9.6
       -name: install dependencies
        run:
           python -m pip install --upgrade pip
           pip install -r requirement.txt
      -name: lint with flake8
        run:
          pip install coverage
          coverage run manage.py test
          coverage report
      -name: Django Testing
        run:
          python3 manage.py test
